import { Movie } from '@/types/movie';

export const sampleMovies: Movie[] = [
  {
    id: 1,
    title: 'Pathaan',
    overview: 'An Indian spy battles a mercenary who has a personal vendetta against him.',
    posterUrl: 'https://placehold.co/300x450/1a1a2e/e50914?text=Pathaan',
    backdropUrl: 'https://placehold.co/1920x800/1a1a2e/e50914?text=Pathaan+Backdrop',
    rating: 7.2,
    genres: ['Action', 'Thriller'],
    releaseYear: 2023,
    runtime: 146,
    releaseDate: '2023-01-25',
    language: 'Hindi',
    country: 'India',
    director: 'Siddharth Anand',
    writers: ['Shouryut'],
    productionCompany: 'Yash Raj Films',
    budget: 25000000,
    revenue: 105000000,
    ageRating: 'UA',
    tagline: 'Fight for the nation',
    trailerUrl: 'https://www.youtube.com/watch?v=vqu4z34wENw',
    cast: [
      { id: 1, name: 'Shah Rukh Khan', character: 'Pathaan', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=SRK' },
      { id: 2, name: 'Deepika Padukone', character: 'Rubina', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Deepika' },
      { id: 3, name: 'John Abraham', character: 'Rudra', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=John' },
    ],
    mood: ['action', 'adventure'],
  },
  {
    id: 2,
    title: 'Jawan',
    overview: 'A man is driven by a personal vendetta to rectify the wrongs in society while keeping a promise made years ago.',
    posterUrl: 'https://placehold.co/300x450/1a1a2e/e50914?text=Jawan',
    backdropUrl: 'https://placehold.co/1920x800/1a1a2e/e50914?text=Jawan+Backdrop',
    rating: 7.6,
    genres: ['Action', 'Thriller'],
    releaseYear: 2023,
    runtime: 169,
    releaseDate: '2023-09-07',
    language: 'Hindi',
    country: 'India',
    director: 'Atlee',
    writers: ['Sumit Arjula', 'Rathna Kumar'],
    productionCompany: 'Red Chillies Entertainment',
    budget: 100000000,
    revenue: 350000000,
    ageRating: 'UA',
    tagline: 'The people\u0027s warrior',
    trailerUrl: 'https://www.youtube.com/watch?v=COv52Qyctws',
    cast: [
      { id: 4, name: 'Shah Rukh Khan', character: 'Vijay/Aditya', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=SRK' },
      { id: 5, name: 'Nayanthara', character: 'Ayesha', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Nayanthara' },
      { id: 6, name: 'Vijay Sethupathi', character: 'Sanjay', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Vijay' },
    ],
    mood: ['action', 'drama'],
  },
  {
    id: 3,
    title: 'Dunki',
    overview: 'Four friends from a village in Punjab share a common dream of going to England, but they lack both tickets and visas.',
    posterUrl: 'https://placehold.co/300x450/0f3460/f1c40f?text=Dunki',
    backdropUrl: 'https://placehold.co/1920x800/0f3460/f1c40f?text=Dunki+Backdrop',
    rating: 7.1,
    genres: ['Comedy', 'Drama'],
    releaseYear: 2023,
    runtime: 161,
    releaseDate: '2023-12-22',
    language: 'Hindi',
    country: 'India',
    director: 'Rajkumar Hirani',
    writers: ['Rajkumar Hirani', 'Abhijit Joshi'],
    productionCompany: 'Red Chillies Entertainment',
    budget: 60000000,
    revenue: 200000000,
    ageRating: 'UA',
    tagline: 'Dream big',
    trailerUrl: 'https://www.youtube.com/watch?v=AK8uegn7ljE',
    cast: [
      { id: 7, name: 'Shah Rukh Khan', character: 'Harday', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=SRK' },
      { id: 8, name: 'Taapsee Pannu', character: 'Manu', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Taapsee' },
    ],
    mood: ['comedy', 'heartwarming'],
  },
  {
    id: 4,
    title: 'Animal',
    overview: 'A son\u0027s love for his father spirals into a dark obsession, leading to a violent confrontation with his family.',
    posterUrl: 'https://placehold.co/300x450/1a1a2e/e50914?text=Animal',
    backdropUrl: 'https://placehold.co/1920x800/1a1a2e/e50914?text=Animal+Backdrop',
    rating: 6.8,
    genres: ['Action', 'Crime', 'Drama'],
    releaseYear: 2023,
    runtime: 201,
    releaseDate: '2023-12-01',
    language: 'Hindi',
    country: 'India',
    director: 'Sandeep Reddy Vanga',
    writers: ['Sandeep Reddy Vanga'],
    productionCompany: 'T-Series',
    budget: 100000000,
    revenue: 500000000,
    ageRating: 'A',
    tagline: 'Love. Power. Revenge.',
    trailerUrl: 'https://www.youtube.com/watch?v=D4O8Z-YQDcI',
    cast: [
      { id: 9, name: 'Ranbir Kapoor', character: 'Rudra', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Ranbir' },
      { id: 10, name: 'Rashmika Mandanna', character: 'Geetanjali', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Rashmika' },
      { id: 11, name: 'Anil Kapoor', character: 'Balbir', profileImage: 'https://placehold.co/150x150/1a1a2e/ffffff?text=Anil' },
    ],
    mood: ['intense', 'drama'],
  },
  {
    id: 5,
    title: 'Oppenheimer',
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    posterUrl: 'https://placehold.co/300x450/2d3436/fdcb6e?text=Oppenheimer',
    backdropUrl: 'https://placehold.co/1920x800/2d3436/fdcb6e?text=Oppenheimer+Backdrop',
    rating: 8.4,
    genres: ['Biography', 'Drama', 'History'],
    releaseYear: 2023,
    runtime: 180,
    releaseDate: '2023-07-21',
    language: 'English',
    country: 'USA',
    director: 'Christopher Nolan',
    writers: ['Christopher Nolan', 'Kai Bird'],
    productionCompany: 'Universal Pictures',
    budget: 100000000,
    revenue: 952000000,
    ageRating: 'R',
    tagline: 'The world forever changes',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    cast: [
      { id: 12, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profileImage: 'https://placehold.co/150x150/2d3436/ffffff?text=Cillian' },
      { id: 13, name: 'Emily Blunt', character: 'Kitty Oppenheimer', profileImage: 'https://placehold.co/150x150/2d3436/ffffff?text=Emily' },
      { id: 14, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profileImage: 'https://placehold.co/150x150/2d3436/ffffff?text=RDJ' },
    ],
    mood: ['intense', 'thoughtful'],
  },
  {
    id: 6,
    title: 'Interstellar',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\u0027s survival.',
    posterUrl: 'https://placehold.co/300x450/0c2461/74b9ff?text=Interstellar',
    backdropUrl: 'https://placehold.co/1920x800/0c2461/74b9ff?text=Interstellar+Backdrop',
    rating: 8.7,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    releaseYear: 2014,
    runtime: 169,
    releaseDate: '2014-11-07',
    language: 'English',
    country: 'USA',
    director: 'Christopher Nolan',
    writers: ['Jonathan Nolan', 'Christopher Nolan'],
    productionCompany: 'Paramount Pictures',
    budget: 165000000,
    revenue: 701729206,
    ageRating: 'PG-13',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    cast: [
      { id: 15, name: 'Matthew McConaughey', character: 'Cooper', profileImage: 'https://placehold.co/150x150/0c2461/ffffff?text=Matthew' },
      { id: 16, name: 'Anne Hathaway', character: 'Brand', profileImage: 'https://placehold.co/150x150/0c2461/ffffff?text=Anne' },
      { id: 17, name: 'Jessica Chastain', character: 'Murph', profileImage: 'https://placehold.co/150x150/0c2461/ffffff?text=Jessica' },
    ],
    mood: ['adventure', 'thoughtful'],
  },
  {
    id: 7,
    title: 'Inception',
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://placehold.co/300x450/2c3e50/ecf0f1?text=Inception',
    backdropUrl: 'https://placehold.co/1920x800/2c3e50/ecf0f1?text=Inception+Backdrop',
    rating: 8.8,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    releaseYear: 2010,
    runtime: 148,
    releaseDate: '2010-07-16',
    language: 'English',
    country: 'USA',
    director: 'Christopher Nolan',
    writers: ['Christopher Nolan'],
    productionCompany: 'Warner Bros.',
    budget: 160000000,
    revenue: 836836967,
    ageRating: 'PG-13',
    tagline: 'Your mind is the scene of the crime',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    cast: [
      { id: 18, name: 'Leonardo DiCaprio', character: 'Cobb', profileImage: 'https://placehold.co/150x150/2c3e50/ffffff?text=Leo' },
      { id: 19, name: 'Joseph Gordon-Levitt', character: 'Arthur', profileImage: 'https://placehold.co/150x150/2c3e50/ffffff?text=Joseph' },
      { id: 20, name: 'Elliot Page', character: 'Ariadne', profileImage: 'https://placehold.co/150x150/2c3e50/ffffff?text=Elliot' },
    ],
    mood: ['intense', 'thoughtful'],
  },
  {
    id: 8,
    title: 'Avatar',
    overview: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
    posterUrl: 'https://placehold.co/300x450/0984e3/74b9ff?text=Avatar',
    backdropUrl: 'https://placehold.co/1920x800/0984e3/74b9ff?text=Avatar+Backdrop',
    rating: 7.9,
    genres: ['Action', 'Adventure', 'Fantasy'],
    releaseYear: 2009,
    runtime: 162,
    releaseDate: '2009-12-18',
    language: 'English',
    country: 'USA',
    director: 'James Cameron',
    writers: ['James Cameron'],
    productionCompany: '20th Century Studios',
    budget: 237000000,
    revenue: 2923706026,
    ageRating: 'PG-13',
    tagline: 'Enter the World of Pandora',
    trailerUrl: 'https://www.youtube.com/watch?v=5PSNL1qE6VY',
    cast: [
      { id: 21, name: 'Sam Worthington', character: 'Jake Sully', profileImage: 'https://placehold.co/150x150/0984e3/ffffff?text=Sam' },
      { id: 22, name: 'Zoe Saldana', character: 'Neytiri', profileImage: 'https://placehold.co/150x150/0984e3/ffffff?text=Zoe' },
      { id: 23, name: 'Sigourney Weaver', character: 'Dr. Grace Augustine', profileImage: 'https://placehold.co/150x150/0984e3/ffffff?text=Sigourney' },
    ],
    mood: ['adventure', 'escapist'],
  },
  {
    id: 9,
    title: 'The Dark Knight',
    overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    posterUrl: 'https://placehold.co/300x450/1e272e/f1c40f?text=Dark+Knight',
    backdropUrl: 'https://placehold.co/1920x800/1e272e/f1c40f?text=Dark+Knight+Backdrop',
    rating: 9.0,
    genres: ['Action', 'Crime', 'Drama'],
    releaseYear: 2008,
    runtime: 152,
    releaseDate: '2008-07-18',
    language: 'English',
    country: 'USA',
    director: 'Christopher Nolan',
    writers: ['Jonathan Nolan', 'Christopher Nolan'],
    productionCompany: 'Warner Bros.',
    budget: 185000000,
    revenue: 1004558444,
    ageRating: 'PG-13',
    tagline: 'Why So Serious?',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    cast: [
      { id: 24, name: 'Christian Bale', character: 'Bruce Wayne', profileImage: 'https://placehold.co/150x150/1e272e/ffffff?text=Christian' },
      { id: 25, name: 'Heath Ledger', character: 'Joker', profileImage: 'https://placehold.co/150x150/1e272e/ffffff?text=Heath' },
      { id: 26, name: 'Aaron Eckhart', character: 'Harvey Dent', profileImage: 'https://placehold.co/150x150/1e272e/ffffff?text=Aaron' },
    ],
    mood: ['intense', 'dark'],
  },
  {
    id: 10,
    title: 'Pulp Fiction',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    posterUrl: 'https://placehold.co/300x450/e74c3c/ffffff?text=Pulp+Fiction',
    backdropUrl: 'https://placehold.co/1920x800/e74c3c/ffffff?text=Pulp+Fiction+Backdrop',
    rating: 8.9,
    genres: ['Crime', 'Drama'],
    releaseYear: 1994,
    runtime: 154,
    releaseDate: '1994-10-14',
    language: 'English',
    country: 'USA',
    director: 'Quentin Tarantino',
    writers: ['Quentin Tarantino', 'Roger Avary'],
    productionCompany: 'Miramax Films',
    budget: 8500000,
    revenue: 213928762,
    ageRating: 'R',
    tagline: 'Just because you are a character doesn\u0027t mean you have character.',
    trailerUrl: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    cast: [
      { id: 27, name: 'John Travolta', character: 'Vincent Vega', profileImage: 'https://placehold.co/150x150/e74c3c/ffffff?text=John' },
      { id: 28, name: 'Samuel L. Jackson', character: 'Jules Winnfield', profileImage: 'https://placehold.co/150x150/e74c3c/ffffff?text=Samuel' },
      { id: 29, name: 'Uma Thurman', character: 'Mia Wallace', profileImage: 'https://placehold.co/150x150/e74c3c/ffffff?text=Uma' },
    ],
    mood: ['dark', 'edgy'],
  },
];

export const allGenres = [
  'Action',
  'Adventure',
  'Animation',
  'Biography',
  'Comedy',
  'Crime',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Thriller',
];

export const allMoods = [
  'action',
  'adventure',
  'comedy',
  'dark',
  'edgy',
  'escapist',
  'heartwarming',
  'intense',
  'romantic',
  'thoughtful',
];

export const allLanguages = ['English', 'Hindi', 'Tamil', 'Telugu', 'Spanish', 'French', 'Japanese', 'Korean'];